# Generated by Django 4.0.5 on 2022-06-07 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/images/')),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
